/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ChatRedPacket_CONSTANTS_H
#define ChatRedPacket_CONSTANTS_H

#include "ChatRedPacket_types.h"

namespace crp {

class ChatRedPacketConstants {
 public:
  ChatRedPacketConstants();

};

extern const ChatRedPacketConstants g_ChatRedPacket_constants;

} // namespace

#endif
