/*
// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ChatRedPacket.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::crp;

class ChatRedPacketHandler : virtual public ChatRedPacketIf {
 public:
  ChatRedPacketHandler() {
    // Your initialization goes here
  }

  void createRedPacket(OperateResultDto& _return, const RedPacketCreateDto& createDto) {
    // Your implementation goes here
    printf("createRedPacket\n");
  }

  void receiveRedPacket(RedPacketReceiveResponseDto& _return, const RedPacketReceiveDto& receiveDto) {
    // Your implementation goes here
    printf("receiveRedPacket\n");
  }

  void queryRedPacketStatus(std::vector<QueryResultRedPacketDto> & _return, const QueryByRedPacketIdDto& queryDto) {
    // Your implementation goes here
    printf("queryRedPacketStatus\n");
  }

  void queryReceiveRedPacketByUser(std::vector<QueryResultReceiveUserDto> & _return, const QueryByUserIdDto& queryDto) {
    // Your implementation goes here
    printf("queryReceiveRedPacketByUser\n");
  }

  void queryCreateRedPacketByUser(std::vector<QueryResultUserDto> & _return, const QueryByUserIdDto& queryDto) {
    // Your implementation goes here
    printf("queryCreateRedPacketByUser\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ChatRedPacketHandler> handler(new ChatRedPacketHandler());
  shared_ptr<TProcessor> processor(new ChatRedPacketProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

*/
